# inspired by https://github.com/circe/circe/blob/46a248e27a838b0a96ee74e4e1c6dab49c04c3dc/.travis.yml

language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

scala:
  - 2.12.6
  - 2.13.0-M4

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk10
  - openjdk10

# No more failures allowed. 2.13 milestones should be effectively built against.
# matrix:
#   allow_failures:
#     - scala: 2.13.0-M4
#     - jdk: oraclejdk10


script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage jacocoAggregate coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
